# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(default='', max_length=100)),
                ('beer_type', models.CharField(default='', max_length=100)),
                ('ml', models.IntegerField(default=330)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
