# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 22:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='owner',
            field=models.ForeignKey(related_name='beers', default=None, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
